WDRT parity
MHKiT-Software/MHKiT-MATLAB pull request #127
Opened 2024-04-30 20:47 UTC by hivanov-nrel

This PR is to address MATLAB parity for:
* PR XX

Below are the list of functions to be added:
- [ ] asdfasdf

Below are list of examples to be added:
- [ ] asdfasdf

Testing:
- [ ] add tests
- [ ] tests are passing

2024-06-12 23:26 UTC, hivanov-nrel commented
Hi @simmsa @rpauly18 I think this is ready for review. The code/tests that I worked are passing locally. 

The only thing that I am unsure about is that comparing the notebooks to python, there are some instances where the values differ. For instance, the extreme design wave height seems suspiciously low. However, the tests are passing using the same data as python so i'm a bit confused on where the difference can be coming from...

2024-06-26 21:09 UTC, simmsa requested changes
@hivanov-nrel, overall this is a great improvement! There are a few failing tests due to file path issues and some files that were not included. I addressed these with specific comments in this PR.

I was able to reproduce the odd output in the extreme_response_contour_example Livescript. This issue is due to the gamma parameter not being correctly mapped to MHKiT-Python. The related issue is here #132. I plan to add a PR from the develop branch that fixes this asap. With a fixed jonswap_spectrum function we get a response that is closer to MHKiT-Python.
![Screenshot 2024-06-26 at 2 48 18 PM](https://github.com/MHKiT-Software/MHKiT-MATLAB/assets/3704572/45a6b3fd-c045-4f4f-9fc5-ef714270d750). 

In extreme_response_contour_example, extreme_response_full_sea_state_example, and short_term_extremes_example I am getting results that are different that python. This is most likely due to randomness introduced not specifically setting a random seed in the `surface_elevation` function. At a minimum we should probably set a seed on the MATLAB side. Looking into the python side, the default seed is none (https://github.com/MHKiT-Software/MHKiT-Python/blob/83a9d6d77841bd9da6f0d494c1df9f4bb43d58b0/mhkit/wave/resource.py#L363) and is random. We should push for setting a seed on the Python side when we have time, as it would be great if the MATLAB and Python notebooks had the same results.

2024-06-26 21:09 UTC, simmsa commented on mhkit/tests/Loads_TestExtreme.m
> +            txtfile = readtable("..\..\examples\data\loads\time_series_for_extremes.txt");
These are causing test failures on MacOS. Can we change these to forward slashes? It seems like MATLAB gracefully handles forward slashes on Windows.

2024-06-26 21:09 UTC, simmsa commented on mhkit/tests/Wave_TestContours.m
> +            file_loc = "..\..\examples\data\wave\WDRT_caluculated_countours.json";
This test is failing for me because I think this files was not included. Can you include this file?

2024-06-26 21:09 UTC, simmsa commented on mhkit/tests/Wave_TestContours.m
> +            file_loc = "..\..\examples\data\wave\Hm0_Te_46022.json";
Can we also change these to forward slashes?

2024-06-26 21:09 UTC, simmsa commented on mhkit/tests/Loads_TestExtreme.m
> +            assertEqual(testCase, stegev_pdf, ste_gev_pdf)
This test is failing for me: 
![Screenshot 2024-06-26 at 2 35 31 PM](https://github.com/MHKiT-Software/MHKiT-MATLAB/assets/3704572/e667933b-bb38-4e7f-ada7-95ebf8d3829c)


The errors are relatively small. Adding a small level of acceptable error `0.00005` seems to fix this. Do you think this is an acceptable fix? ![Screenshot 2024-06-26 at 2 37 10 PM](https://github.com/MHKiT-Software/MHKiT-MATLAB/assets/3704572/566afdd2-3bcf-4439-966f-28d847a868ef)

2024-07-01 23:14 UTC, simmsa reviewed
@hivanov-nrel thank you for fixing all the requested items. All of the tests are passing locally. I am going to go ahead and merge this into develop. Thank you for getting this done!

![image](https://github.com/MHKiT-Software/MHKiT-MATLAB/assets/3704572/80d68c08-411e-4748-a140-f7c2febe91bc)

2024-07-01 23:16 UTC, simmsa approved these changes

2024-07-01 23:16 UTC, merged