Adding the uncrossing analysis functions coded in MATLAB
MHKiT-Software/MHKiT-MATLAB pull request #151
Opened 2024-12-16 18:21 UTC by MShabara

This PR is related to the uncrossing analysis utilities:
1- The upcrossing functions were added.
2- The upcrossing_Test unit test is added.

2024-12-18 15:56 UTC, simmsa commented
@MShabara, if this is ready to go can you please add @rpauly18 and myself as reviewers? If not can you convert this to a draft?

2025-01-28 23:06 UTC, simmsa requested changes
@MShabara, overall the implementation looks good and I don't see any technical errors. Could you please:
1. Update the docstrings to follow this projects format
2. Address the inline comments I've left about test file locations, unused code, and citations

2025-01-28 23:06 UTC, simmsa commented on mhkit/tests/upcrossing_Test.m
> +    % end
Can we remove this code?

2025-01-28 23:06 UTC, simmsa commented on mhkit/tests/waveform_signal.txt
Can you move this to `examples/data/utils` ?

2025-01-28 23:06 UTC, simmsa commented on mhkit/utils/upcrossing/README.md
> +- **mshabara**
Can we cite the original authors of this code also? https://github.com/MHKiT-Software/MHKiT-Python/blob/bc1eadc9117f969bed618a104834892bff1e3df0/mhkit/utils/upcrossing.py#L16-L19

2025-01-28 23:06 UTC, simmsa commented on mhkit/utils/upcrossing/uc_apply_.m
> +    %   vals : Array of values resulting from applying `f` over the intervals defined by `inds`.
Docstrings need to follow this projects docstring format, which is used by [sphinx-matlabdomain](https://github.com/sphinx-contrib/matlabdomain) to generate the MHKiT-MATLAB website documentation. For consistency, please reference the format shown in [delft_3d_calculate_variable_interpolation.m](https://github.com/MHKiT-Software/MHKiT-MATLAB/blob/develop/mhkit/river/IO/delft_3d/delft_3d_calculate_variable_interpolation.m) in the MHKiT-MATLAB repository. This gets rendered [here](https://mhkit-software.github.io/MHKiT/mhkit-matlab/api.river.html#mhkit.river.IO.delft_3d.delft_3d_calculate_variable_interpolation).

At this time I cannot find any specific documentation for this format. I'll update our contributor documentation to include these docstring specifications for future reference. 

For this function the docstring should be:

```
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% Apply a function over defined intervals in time series data.
%
% Parameters
% ------------
%     t: array
%         Array of time values.
%     data: array
%         Array of data values.
%     f: function handle
%         Function that takes two indices (start, end) and returns a scalar value.
%     inds: array, optional
%         Indices array defining the intervals. If not provided, intervals will be
%         computed using the upcrossing function.
%
% Returns
% ---------
%     vals: array
%         Array of values resulting from applying the function over the defined intervals.
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

2025-01-28 23:06 UTC, simmsa commented on mhkit/utils/upcrossing/uc_apply_.m
> +    vals = zeros(1, n);       % Initialize the output array
Do you think the `vals` array should be initialized as zeros? If `f` fails to return would that leave unintended zeroes in the output? Maybe it would be better to initialize the output `vals` array as NaNs?

2025-02-03 17:15 UTC, MShabara commented on mhkit/tests/waveform_signal.txt
This file was for testing the functions, it is no longer needed. I deleted it.

2025-02-03 17:16 UTC, MShabara commented on mhkit/utils/upcrossing/README.md
> +- **mshabara**
Done.

2025-02-03 17:16 UTC, MShabara commented on mhkit/utils/upcrossing/uc_apply_.m
> +    %   vals : Array of values resulting from applying `f` over the intervals defined by `inds`.
Done.

2025-02-03 17:16 UTC, MShabara commented on mhkit/utils/upcrossing/uc_apply_.m
> +    vals = zeros(1, n);       % Initialize the output array
This is a good idea. I applied this change.

2025-02-03 18:38 UTC, simmsa commented on examples/adcp_example.mlx
`adcp_example.mlx` seems unrelated to the upcrossing analysis changes. If it's not specifically needed for this feature, could we revert this change to keep the PR focused? You should be able to run `git checkout origin/develop -- examples/adcp_example.mlx` to revert back to the version on the develop branch.

2025-02-03 18:40 UTC, simmsa commented on examples/environmental_contours_example.mlx
As above - is this change needed for the upcrossing analysis? If not, please revert using git checkout origin/develop -- <path to file>

2025-02-03 18:40 UTC, simmsa commented on examples/extreme_response_contour_example.mlx
As above - is this change needed for the upcrossing analysis? If not, please revert using git checkout origin/develop -- <path to file>

2025-02-03 18:41 UTC, simmsa commented on examples/short_term_extremes_example.html
As above - is this change needed for the upcrossing analysis? If not, please revert using git checkout origin/develop -- <path to file>

2025-02-03 18:41 UTC, simmsa commented on examples/short_term_extremes_example.mlx
As above - is this change needed for the upcrossing analysis? If not, please revert using git checkout origin/develop -- <path to file>

2025-02-03 18:41 UTC, simmsa commented on examples/wave_example.mlx
As above - is this change needed for the upcrossing analysis? If not, please revert using git checkout origin/develop -- <path to file>

2025-02-03 18:42 UTC, simmsa commented on mhkit/wave/resource/energy_period.m
This will be added in #149. Can we please revert this here in favor of all the changes in #149.

2025-02-03 18:43 UTC, simmsa commented on mhkit/wave/resource/significant_wave_height.m
This is fixed in #149. Can we please revert this in favor of the changes in #149?

2025-02-03 18:44 UTC, simmsa commented on mhkit_python_utils/pandas_dataframe.py
`spectra_to_pandas_v2` seems ok to keep, but can we remove the debug statements? Maybe this also falls outside the scope of this PR?

2025-02-03 18:54 UTC, simmsa commented on mhkit/utils/upcrossing/uc_apply_.m
> +    %   vals : Array of values resulting from applying `f` over the intervals defined by `inds`.
Thanks! Docstrings look good.

2025-02-03 21:30 UTC, MShabara commented on examples/environmental_contours_example.mlx
fixed it using 
`git fetch origin`
`git merge origin/develop`
`git push origin upcrossing`

2025-02-03 22:42 UTC, simmsa approved these changes

2025-02-04 17:55 UTC, simmsa commented
@MShabara, this looks good and all tests are passing. Thank you for your work on this! I am going to merge this into develop via a merge commit.

2025-02-04 18:00 UTC, merged